### ISSUE TITLE
pushing strings in a multi-project environment raises 4048 error

### ISSUE THREAD

**Issue by mick88** [mick88/poeditor-sync#12]
The tool adds time interval between languages when pushing translations, but if multiple projects are defined, no such interval is added between last language of first project, and first language of next project. This causes POEditor to reject request.

Example: pushing arabic translations for environment having two projects:
```
$ poeditor -l ar push
Pushing PROJECT1 translations... ar
Pushing PROJECT2 translations... arTraceback (most recent call last):
  File "C:\Users\Michal\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Michal\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Michal\src\mat-cms\Scripts\poeditor.exe\__main__.py", line 7, in <module>
  File "C:\Users\Michal\src\mat-cms\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Michal\src\mat-cms\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Michal\src\mat-cms\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Michal\src\mat-cms\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Michal\src\mat-cms\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Michal\src\mat-cms\lib\site-packages\click\decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "C:\Users\Michal\src\mat-cms\lib\site-packages\poeditor_sync\cmd.py", line 87, in push_translations
    client.update_terms_translations(
  File "C:\Users\Michal\src\mat-cms\lib\site-packages\poeditor\client.py", line 670, in update_terms_translations
    return self._upload(
  File "C:\Users\Michal\src\mat-cms\lib\site-packages\poeditor\client.py", line 594, in _upload
    data = self._run(
  File "C:\Users\Michal\src\mat-cms\lib\site-packages\poeditor\client.py", line 138, in _run
    return self._make_request(url, payload, headers)
  File "C:\Users\Michal\src\mat-cms\lib\site-packages\poeditor\client.py", line 121, in _make_request
    raise POEditorException(
poeditor.client.POEditorException: Status 'fail', code 4048: Too many upload requests in a short period of time
```

**Comment by mick88** [comment]
fixed on master
